import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@600;700&display=swap" rel="stylesheet"></link>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.tomeiImg}>
        <Image 
        src="/Logo.png" 
        layout="responsive" 
        width={188} 
        height={54}/>
        </div>

        <div class="grid grid-cols-9 gap-0 justify-items-end items-center max-w-2xl mt-5">
          <img class="z-10 -ml-10" src="/Wizard-Step1.png" width="72" height="93"></img>
          <img class="-ml-10" src="/Wizard-HorizontalBar.png" width="101" height="3"></img>

          <img class="z-10 -ml-10" src="/Wizard-Step2.png" width="72" height="93"></img>
          <img class="-ml-10" src="/Wizard-HorizontalBar.png"  width="101" height="3"></img>

          <img class="z-10 -ml-10" src="/Wizard-Step3.png" width="72" height="93"></img>
          <img class="-ml-10" src="/Wizard-HorizontalBar.png"  width="101" height="3"></img>

          <img class="z-10 -ml-10" src="/Wizard-Step4.png" width="72" height="93"></img>
          <img class="-ml-10" src="/Wizard-HorizontalBar.png"  width="101" height="3"></img>

          <img class="z-10 -ml-10" src="/Wizard-Step5.png" width="72" height="93"></img>
            
        </div>

        <div class="grid grid-cols-5 gap-14">
          <div class="grid grid-rows-2 gap-0 text-center max-w-[72px] text-base">
            <p class="text-base font-bold">STEP 1:</p>
            <p class="-mt-8 font-semibold">CREATE YOUR ACCOUNT PASSWORD</p>
          </div>
          <div class="grid grid-rows-2 gap-0 text-center  max-w-[72px]  text-base">
            <p class="text-base font-bold">STEP 2:</p>
            <p class="-mt-8 font-semibold">PERSONAL INFORMATION</p>
          </div>
          <div class="grid grid-rows-2 gap-0 text-center  max-w-[72px] text-base">
            <p class="text-base font-bold">STEP 3:</p>
            <p class="-mt-8 font-semibold">EMPLOYMENT DETAILS</p>
          </div>
          <div class="grid grid-rows-2 gap-0 text-center  max-w-[72px]  text-base">
            <p class="text-base font-bold">STEP 4:</p>
            <p class="-mt-8 font-semibold">UPLOAD DOCUMENTS</p>
          </div>
          <div class="grid grid-rows-2 gap-0 text-center  max-w-[72px]  text-base">
            <p class="text-base font-bold">STEP 5:</p>
            <p class=" -mt-8 font-semibold">COMPLETE</p>
          </div>
        </div>

        <div className={styles.inputContainer}>
          <div className={styles.createAcc}>
            <p>
              CREATE YOUR ACCOUNT
            </p>
          </div>

          <p className={styles.createDesc}>
              Because there will be documents thet you need to prepare to apply for loan,
              let's start off by creating a password that you can login to your account once you have
              these documents ready.
          </p>

          <div class="grid grid-rows-2 grid-flow-col gap-4 items-center justify-items-center">
            <div class="row-span-2">
              <img class="" src="/Avatar.png" width="131" height="136"></img>
              <p className={styles.uploadText}>Upload</p>
            </div>
            <form class='grid grid-rows-2'>
              <label className={styles.inputLabel}>Name</label>
              <input className={styles.inputBorder} type="text" id="first" name="first" />
            </form>
            <form class='grid grid-rows-2'>
              <label className={styles.inputLabel}>Password</label>
              <input className={styles.inputBorder} type="text" id="first" name="first" />
            </form>
            <form class='grid grid-rows-2'>
              <label className={styles.inputLabel}>Email</label>
              <input className={styles.inputBorder} type="text" id="first" name="first" />
            </form>
            <form class='grid grid-rows-2'>
              <label className={styles.inputLabel}>Confirm Password</label>
              <input className={styles.inputBorder} type="text" id="first" name="first" />
            </form>
          </div>

          <div class="grid grid-rows-1 grid-flow-col gap-4 text-right mt-8">
            <form>
              <button className={styles.buttonSave} type="submit">
                <p>SAVE & NEXT →</p></button>
            </form>
          </div>
        </div>

      </main>
    </div>
  )
}
